### ISSUE TITLE
[Compatibility Request]: Extra Utilties

### ISSUE THREAD

**Issue by RubenFasola** [FalsePattern/EndlessIDs#10]
### Other mod's name

Extra Utilities

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/extra-utilities

### Other mod's license

All Rights Reserved

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/9086164/fml-client-latest.log)

**Comment by FalsePattern** [comment]
Fixed in 1.4 Alpha 10
