### ISSUE TITLE
Question for version 1.12.2

### ISSUE THREAD

**Issue by GamebP** [FalsePattern/EndlessIDs#100]
# <p align="center">_Hey false._</p>
<strong>I know you are good beginer by creating good mods that are useful! I support you but in the future is it possoble to do it on 1.12.2 or no?</strong>

### Beacuse
* The 1.12.2 version offers more stability and compatibility with other mods.
* The 1.12.2 version has more features and updates than 1.7.10.
* The 1.12.2 version allows for more complex and advanced modding, which can create more interesting and immersive experiences for players.

**No need to rush but just asking.** 
_Beacuse 1.12.2 cannot support 1.7.10_

**Comment by swiftyflow01** [comment]
1.12.2 or higher has more ids for biomes probably
eids is useless on 1.12.2

**Comment by FalsePattern** [comment]
I only develop mods for the superior 1.7.10 version.

**Comment by FalsePattern** [comment]
As for more "complex" mods, coremods in 1.7.10 can be as conplex as you want them to be.

**Comment by FalsePattern** [comment]
As for more "complex" mods, coremods in 1.7.10 can be as conplex as you want them to be.

See also:
https://reikakalseki.github.io/minecraft/pages/info/updating.html
this article has a lot of great talking points about why developing mods past 1.7.10 is actually *more* restrictive than staying on 1.7.10.
