### ISSUE TITLE
[Bug]: Crash when tp to the abyssalcraft dimension "Omothol" with the 1.5 Alpha 5(fixed when use the 1.5 Alpha 3)

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/EndlessIDs#101]
### OS

Windows

### GPU

NVIDIA

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/10902990/fml-client-latest.log)

### Description

Its a crash about java.lang.ArrayIndexOutOfBoundsException

Use /cofh tpx "Omothol dimension id", and get crash

**Comment by quentin452** [comment]
crash fixed when disabling extendBlockItem

**Comment by FalsePattern** [comment]
See #103 for more info
