### ISSUE TITLE
[Bug]: If any biome mod (BOP, EBXL, etc.) is installed, the game crashes upon entering a world.

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/EndlessIDs#103]
### OS

Windows

### GPU

AMD

### Modpack (Optional)

N/A

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/10915197/fml-client-latest.log)

### Description

Title.

![image](https://user-images.githubusercontent.com/51277766/223586750-59808c2c-bb06-4063-9f2b-d226d610cad1.png)

**Comment by quentin452** [comment]
seem to be duplicated #101

**Comment by FalsePattern** [comment]
It seems like this was a bug in the netcode implementation. Should be fixed in alpha0006, the shaky mixin hacks have been replaced with ChunkAPI as the network/saving backend.

Please check if this still happens in the latest versions

**Comment by MagmaBro123** [comment]
Yep, seems to be fixed.
