### ISSUE TITLE
[Compatibility Request]: Restructured

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/EndlessIDs#105]
### Other mod's name

org.blockartistry.mod.Restructured

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/restructured

### Other mod's license

MIT

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/10927795/fml-client-latest.log)

### Description

Crash when make a world

**Comment by FalsePattern** [comment]
Fix scheduled for 1.5 alpha 7

**Comment by quentin452** [comment]
fixed
