### ISSUE TITLE
[Compatibility Request]: Fastcraft

### ISSUE THREAD

**Issue by branman5949** [FalsePattern/EndlessIDs#108]
### Other mod's name

Fastcraft

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/fastcraft

### Other mod's license

All Rights Reserved

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/11025295/fml-client-latest.log)

### Description
Incompatible with EndlessIDs 1.5 Alpha 0005
[crash-2023-03-21_01.41.31-server.txt](https://github.com/FalsePattern/EndlessIDs/files/11025289/crash-2023-03-21_01.41.31-server.txt)

**Comment by MagmaBro123** [comment]
Use other optimization mods. FastCraft is closed-source, buggy, and not worth using.

**Comment by FalsePattern** [comment]
FastCraft has been obsoleted by mods such as FalseTweaks, ArchaicFix, bugtorch, etc., please use those instead, they are both more modern and also not obfuscated.
