### ISSUE TITLE
[Bug]: Strange bug on custom modpack

### ISSUE THREAD

**Issue by EretikBoy** [FalsePattern/EndlessIDs#109]
### OS

Windows

### GPU

AMD

### Game log

[crash-2023-03-22_01.52.44-client.txt](https://github.com/FalsePattern/EndlessIDs/files/11034682/crash-2023-03-22_01.52.44-client.txt)

### Description

i was hoping that this mod will help with ids problem which presents in this very strange custom modpack, but it's seems that mod itself can't apply some methods to smth

**Comment by swiftyflow01** [comment]
after all you can close this issue

**Comment by EretikBoy** [comment]
ty =3
