### ISSUE TITLE
[Bug]: crash with dimensional doors

### ISSUE THREAD

**Issue by PopcornHead51** [FalsePattern/EndlessIDs#111]
### OS

Windows

### GPU

NVIDIA

### Game log

[latest.log](https://github.com/FalsePattern/EndlessIDs/files/11054043/latest.log)

### Description

The game crashes on startup saying there's a biome id conflict with Dimensional Doors no matter what the ids are in the config.

**Comment by FalsePattern** [comment]
Fix scheduled for 1.5 alpha 7

**Comment by FalsePattern** [comment]
Fixed in alpha 7
