### ISSUE TITLE
[Bug]: ModularUI mixin collision in net.minecraft.network.PacketBuffer

### ISSUE THREAD

**Issue by swiftyflow01** [FalsePattern/EndlessIDs#112]
### OS

Windows

### GPU

NVIDIA

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/11131381/fml-client-latest.log)

### Description

crashing with modularui when entering into the world
also having a huge log spam when endlessids spotting a missing mod

**Comment by FalsePattern** [comment]
Notes for self:
func_150788_a
com.falsepattern.endlessids.mixin.mixins.common.blockitem.vanilla.PacketBufferMixin

**Comment by FalsePattern** [comment]
Fix planned in alpha 7

**Comment by swiftyflow01** [comment]
so Modularui works
