### ISSUE TITLE
[Bug]: Server crash when join the server with endlessids 1.5 alpha 7

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/EndlessIDs#117]
### OS

Windows

### GPU

NVIDIA

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/11221053/fml-client-latest.log)

### Description

this issue doesn't appear when join a world in the client 

mods lists : 

_unimixins-all-1.7.10-0.1.6
falsepatternlib-mc1.7.10-0.11.2
chunkapi-mc1.7.10-0.1.1
endlessids-mc1.7.10-1.5-alpha0007

**Comment by FalsePattern** [comment]
Fixed in ChunkAPI 0.1.2
