### ISSUE TITLE
[Bug]: Crash on server on startup caused by asjcore and endlessids

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/EndlessIDs#120]
### OS

Windows

### GPU

NVIDIA

### Game log

[fml-server-latest.log](https://github.com/FalsePattern/EndlessIDs/files/11302592/fml-server-latest.log)

### Description

Crash when make  a world on server 

Fixed when i remove ASJCORE or endlessids

**Comment by quentin452** [comment]
workaround can be fixed by using 1.7.10-ASJCore-1.1.2.3

**Comment by Darkpixel797** [comment]
I have the same issue, here is the crash report:
[crash-2023-07-28_12.04.08-server.txt](https://github.com/FalsePattern/EndlessIDs/files/12196253/crash-2023-07-28_12.04.08-server.txt)

**Comment by quentin452** [comment]
duplicated #142
