### ISSUE TITLE
[Compatibility Request?]: World's made with Not enough ids

### ISSUE THREAD

**Issue by geepers134** [FalsePattern/EndlessIDs#123]
### Other mod's name

Not enough ids

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/notenoughids

### Other mod's license

MIT

### Game log

no crash

### Description

It can load NEID worlds fine all blocks above 4096 vanish.
I did some digging around in the chunk files to wrap my own head around it, NEID writes every block above 4096 to its own array with 2 bytes per block, but upon messing around and taking that array and splitting it across the arrays endless ids can read it loads up those blocks just fine. Is it possible for endless ids to do such a thing if it detects it loads a NEID world? Or is this something better suited for an external program.

**Comment by lordmuff** [comment]
i have a world made with NotEnoughIDs and i can corroborate that this is an issue. happened to me just now. can provide more info if you need it.

would love to see this as a feature in 1.5 because otherwise it seems to work flawlessly.

**Comment by lordmuff** [comment]
> ### Other mod's name
> 
> Not enough ids
> ### Other mod's homepage
> 
> https://www.curseforge.com/minecraft/mc-mods/notenoughids
> ### Other mod's license
> 
> MIT
> ### Game log
> 
> no crash
> ### Description
> 
> It can load NEID worlds fine all blocks above 4096 vanish. I did some digging around in the chunk files to wrap my own head around it, NEID writes every block above 4096 to its own array with 2 bytes per block, but upon messing around and taking that array and splitting it across the arrays endless ids can read it loads up those blocks just fine. Is it possible for endless ids to do such a thing if it detects it loads a NEID world? Or is this something better suited for an external program.

side note, can you tell me how you managed to "split the arrays"? would love to do this for myself in the meantime

**Comment by geepers134** [comment]
> 

I don't remember the process well but i exported the Blocks16 array with nbt explorer, used a hexeditor to copy it into notepad++ as each row being 2 bytes, and then using alt select to select a column to paste into NBT Studio (it first needs to be copied as a row of values like 00 00 otherwise it will paste them in wrongly, and using NBT Studio because it interprets 0 as 0 rather than the ansi value of 30 that explorer does) and once each array edited in NBT Studio u save the map and that one 16x16x16 chunk will have blocks above 4096 : ) 
so something like 28D7 in Block16 gets split up into 2 in BlocksB2Hi, 8 in Add, and D7 in Blocks, Neid doesnt write block ids to Add or Blocks because it uses its own array.
But you can see why this isn't viable for editing an entire map, and i remember somehow one of the arrays not lining up to the others but that is most likely an issue with pasting.

**Comment by FalsePattern** [comment]
Added a DFU for NEID saves in alpha 8.

**Comment by lordmuff** [comment]
the StatList regression fix is causing an InvocationTargetException when trying to apply it's mixin in my modlist.
logs attached, i'm also investigating on my own to narrow down what it's conflicting with...
[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/11416027/fml-client-latest.log)

**Comment by lordmuff** [comment]
tested it in a minimal instance; happens with ONLY EndlessIDs and dependencies installed. opening a new issue.

**Comment by geepers134** [comment]
the new alpha works great, all blocks >4096 load and I cant see any apparent issues, thank you!
