### ISSUE TITLE
[Bug]: Crashes.

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/EndlessIDs#125]
### OS

Windows

### GPU

AMD

### Game log

[latest.log](https://github.com/FalsePattern/EndlessIDs/files/11417104/latest.log)
[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/11417105/fml-client-latest.log)

### Description

Game crashes.

**Comment by FalsePattern** [comment]
See #124
