### ISSUE TITLE
[Compatibility Request]: Unmined Map Viewer

### ISSUE THREAD

**Issue by lordmuff** [FalsePattern/EndlessIDs#128]
### Other mod's name

Unmined Map Viewer

### Other mod's homepage

https://unmined.net/

### Other mod's license

AGPLv3

### Game log

N/A, external program

### Description

When loading up a world made with EndlessIDs in the Unmined map viewer program, nothing at all shows up.

**Comment by FalsePattern** [comment]
Unmined is not AGPLv3, it's closed source proprietary trash.
I can't do anything on my side, tell the unmined developers do add compatibility instead.
![garbage](https://github.com/FalsePattern/EndlessIDs/assets/30945458/360f3396-1e24-49ec-8e40-e19e85a7b1f4)
