### ISSUE TITLE
[Bug]: Maximum id range Exceeded

### ISSUE THREAD

**Issue by Rimusp** [FalsePattern/EndlessIDs#147]
### OS

Windows

### GPU

AMD

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/12565737/fml-client-latest.log)

### Description
I have no idea which mod is causing this all i know is that everything works fine if i use Not enough ids+ extended potions and if i remove enough mods it will start and launch normal.

Edit: OreSpawn is the reason i tried endless ids as i run out of entity ids but this has nothing todo with the crash happens without it just forgot to remove it

**Comment by FalsePattern** [comment]
open `endlessids.cfg` and try increasing `extraBlockIDBits`.

**make sure you read the comment above it**

**Comment by Rimusp** [comment]
Thanks. Should have checked the config first feeling dumb now lol
