### ISSUE TITLE
[Compatibility Request]: FrozenLand

### ISSUE THREAD

**Issue by branman5949** [FalsePattern/EndlessIDs#22]
### OS

Windows

### GPU

NVIDIA

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/9116733/fml-client-latest.log)

### Description

[crash-2022-07-14_20.23.10-server.txt](https://github.com/FalsePattern/EndlessIDs/files/9116737/crash-2022-07-14_20.23.10-server.txt)

**Comment by FalsePattern** [comment]
This is an incompatibility with the "FrozenLand" mod, however, i cannot find any download link for it.

Please post a download link for the "FrozenLand" mod, otherwise i cannot help you.

**Comment by FalsePattern** [comment]
On further inspection, your modpack has a huge amount of mods that are probably extremely incompatible without a patch. You should use 1.3.0 for now and wait until 1.4 goes out of alpha.

**Comment by quentin452** [comment]
> This is an incompatibility with the "FrozenLand" mod, however, i cannot find any download link for it.
> 
> Please post a download link/homepage URL/curseforge URL for the "FrozenLand" mod, otherwise i cannot help you.

i think this is this mod https://www.9minecraft.net/frozenland-mod/ , but the mod is working with endlessid
