### ISSUE TITLE
[Compatibility Request]: Incompatible with SpongeMixins

### ISSUE THREAD

**Issue by zerozaki666** [FalsePattern/EndlessIDs#23]
### Other mod's name

SpongeMixins

### Other mod's homepage

https://modrinth.com/mod/spongemixin1710

### Other mod's license

MIT

### Game log

|useless stacktrace removed|

### Description

It seems to crash with SpongeMixins.

**Comment by embeddedt** [comment]
[Mixingasm](https://github.com/makamys/Mixingasm/releases/tag/v0.2.1) might also help.

**Comment by FalsePattern** [comment]
post the entire game log file, this crash report tells me nothing.

This mod is *designed* to work with SpongeMixins 1.2.0, so it's most likely a conflict with a different mod, but again, i need the **entire** game log, not just the crash message.

**Comment by zerozaki666** [comment]
Finally figured it out with one by one mod disabled, it was crashing with LagGoggles Legacy. 
https://modrinth.com/mod/lglegacy
And the entire log is right here.
https://pastebin.com/ppMPx37b

Actually I don't need LagGoggles, just remove it and play it well.
