### ISSUE TITLE
[Regression]: Item/Block ID limit broken

### ISSUE THREAD

**Issue by branman5949** [FalsePattern/EndlessIDs#28]
### OS

Windows

### GPU

NVIDIA

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/9142446/fml-client-latest.log)

### Description

[crash-2022-07-19_11.15.59-client.txt](https://github.com/FalsePattern/EndlessIDs/files/9142454/crash-2022-07-19_11.15.59-client.txt)

**Comment by FalsePattern** [comment]
fixed in beta 2
