### ISSUE TITLE
NoClassDefFoundError: net/minecraft/world/chunk/storage/AnvilChunkLoader ???

### ISSUE THREAD

**Issue by branman5949** [FalsePattern/EndlessIDs#31]
### OS

Windows

### GPU

NVIDIA

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/9174580/fml-client-latest.log)

### Description

[crash-2022-07-23_16.13.52-server.txt](https://github.com/FalsePattern/EndlessIDs/files/9174581/crash-2022-07-23_16.13.52-server.txt)

**Comment by FalsePattern** [comment]
ah, this is completely my fault
i already had the fix for that implemented, i just forgot to commit it
Beta 2 hotfix 1 releasing in a few minutes, that solves this problem
