### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Darkpixel797** [FalsePattern/EndlessIDs#34]
### OS

Windows

### GPU

NVIDIA

### Modpack (Optional)

Arcane Reality 1.29

### Game log

[fml-server-latest.log](https://github.com/FalsePattern/EndlessIDs/files/9178068/fml-server-latest.log)

### Description

Works fine clientside but upon trying to launch my server this happens.

**Comment by FalsePattern** [comment]
Remove NEID. EndlessIDs replaces NEID.
