### ISSUE TITLE
[Compatibility Request]: Random Things

### ISSUE THREAD

**Issue by TheDrewskey** [FalsePattern/EndlessIDs#37]
### Other mod's name

Random Things

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/random-things

### Other mod's license

MIT

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/9275734/fml-client-latest.log)

### Description

Whenever the Biome Painter is used the game crashes.

**Comment by FalsePattern** [comment]
Fixed in 1.4 beta 3
