### ISSUE TITLE
[Compatibility Request]: Compact Machines

### ISSUE THREAD

**Issue by TheDrewskey** [FalsePattern/EndlessIDs#38]
### Other mod's name

Compact Machines

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/compact-machines

### Other mod's license

Other open source license (please specify in the description)

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/9275754/fml-client-latest.log)

### Description

The game crashes whenever you enter Compact Machine.

The license is "GNU LESSER GENERAL PUBLIC LICENSE"

**Comment by FalsePattern** [comment]
Fixed in 1.4 beta 3
