### ISSUE TITLE
[Compatibility Request]: Et Futurum Requiem

### ISSUE THREAD

**Issue by zuiBaratheon** [FalsePattern/EndlessIDs#39]
### Other mod's name

Et Futurum Requiem

### Other mod's homepage

https://modrinth.com/mod/etfuturum/

### Other mod's license

All Rights Reserved

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/9276814/fml-client-latest.log)

### Description

The launcher cannot start Minecraft

**Comment by zuiBaratheon** [comment]
sorry,i don't know how to acquire mod's license.If u need,i will try.

**Comment by FalsePattern** [comment]
Fixed in 1.4 beta 3

**Comment by zuiBaratheon** [comment]
Hello，this crash is related to DragonAPI and Witching Gadgets has the same situation when I start game with EndlessIDs and DragonAPI.
Thank U&nbsp;


Alexios
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FalsePattern/EndlessIDs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月26日(星期五) 凌晨4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FalsePattern/EndlessIDs] [Compatibility Request]: Et Futurum Requiem (Issue #39)





 
Reopened #39.

**Comment by zuiBaratheon** [comment]
Sorry，i have tried starting Minecraft again with the new vision,the problem of Witching Gadgets has been solved.&nbsp;




Alexios
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FalsePattern/EndlessIDs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月26日(星期五) 凌晨4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FalsePattern/EndlessIDs] [Compatibility Request]: Et Futurum Requiem (Issue #39)





 
Reopened #39.

**Comment by zuiBaratheon** [comment]
I try Et Futurum Requiem 2.3.1-an old version only to find that it does suceess to launch Minecraft.However,it fails when the Et Futurum Requiem's version is 2.4.0.( Maybe the information is useful for you to solve the problem.)

**Comment by FalsePattern** [comment]
Should work with the latest version of GasStation
