### ISSUE TITLE
[Bug]: ATG hates EIDs.

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/EndlessIDs#4]
### OS

Windows

### GPU

AMD

### Game log

https://pastebin.com/WLXCRtNP

[latest.log](https://github.com/FalsePattern/EndlessIDs/files/9032350/latest.log)

Ping me on Roadhog's server if you want any more info.

### Description

Title.

**Comment by FalsePattern** [comment]
Fixed in 413a113a4c38f94c760aa86be0ae2bdeb6fe320b
