### ISSUE TITLE
[Compatibility Request]: Buildcraft

### ISSUE THREAD

**Issue by 0xKate** [FalsePattern/EndlessIDs#40]
### Other Mods Name
Buildcraft

### Other Mods Homepage
https://www.curseforge.com/minecraft/mc-mods/buildcraft/files/3538651

### Other mod's license

Minecraft Mod Public License Version 1.0.1
https://github.com/BuildCraft/BuildCraft/blob/8.0.x-1.12.2/LICENSE
Mozilla Public License Version 2.0
https://github.com/BuildCraft/BuildCraft/blob/8.0.x-1.12.2/LICENSE-NEW

### Game log

[crash-2022-08-21_19.37.02-client.txt](https://github.com/FalsePattern/EndlessIDs/files/9390531/crash-2022-08-21_19.37.02-client.txt)
[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/9390532/fml-client-latest.log)

### Description

Hi, thanks for working on this mod! I found a strange bug with buildcraft, currently in my buildcraft main.cfg I have set the following lines:
```
    biomes {
        I:biomeOilDesert=249

        # The id for the Oil Ocean biome
        I:biomeOilOcean=250
 ```
However when I install in endlessIDs for some reason buildcraft thinks the ID is occupied and tries to find a new one, the buildcraft main.cfg changes to this:

```
    biomes {
        I:biomeOilDesert=78

        # The id for the Oil Ocean biome
        I:biomeOilOcean=250
```
And the game crashes due to buildcraft thinking there are no id's left.

```
buildcraft.BuildCraftEnergy$1BiomeIdLimitException: You have run out of free Biome ID spaces for oilOcean - free more Biome IDs or disable the biome by setting the ID to 0!
```

 (some custom Id searching code that cannot be disabled by config)
```
at buildcraft.BuildCraftEnergy.findUnusedBiomeID(BuildCraftEnergy.java:451)
```

**Comment by FalsePattern** [comment]
Fixed in 1.4 beta 3
