### ISSUE TITLE
[Bug]: Some crash issue with your latest FPLib version and EIDs.

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/EndlessIDs#41]
### OS

Windows

### GPU

AMD

### Game log

Log: https://pastebin.com/PpbXU3Zq
Crash Report File: https://pastebin.com/4NFrQMqP

### Description

Title.

**Comment by FalsePattern** [comment]
this was an fplib issue, fixed in 0.10.5 over there

**Comment by MagmaBro123** [comment]
Ah, sorry then
