### ISSUE TITLE
[Compatibility Request]: DraconicMinus-

### ISSUE THREAD

**Issue by zuiBaratheon** [FalsePattern/EndlessIDs#43]
### Other mod's name

DraconicMinus-

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/draconicminus

### Other mod's license

MIT

### Game log

[crash-2022-08-29_23.27.16-client.txt](https://github.com/FalsePattern/EndlessIDs/files/9446282/crash-2022-08-29_23.27.16-client.txt)

### Description

Hello，DraconicMinus- is an additional mod for DraconicEvolution.It crashed when I add EndlessIDs to my modpack.

**Comment by quentin452** [comment]
for me dracominus no problem with endlessid
