### ISSUE TITLE
[Compatibility Request]: Enderlicious

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/EndlessIDs#48]
### OS

Linux/BSD

### GPU

NVIDIA

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/9473905/fml-client-latest.log)

### Description

Mods list : 

enderlicious-1.1.2
endlessids-mc1.7.10-1.4.0-beta0003
falsepatternlib-mc1.7.10-0.10.8
HardcoreEnderExpansion-1.7.10-1.9.3-GTNH
SpongeMixins-1.5.0

Step to reproduce :

1 : Make a world
2 : Crash

If i use Hardcore Ender Expansion + Enderlicious with endlessid (crash)
If i use Hardcore Ender Expansion without Enderlicious with endlessid and vice versa(don't crash)
If i use Hardcore Ender Expansion + Enderlicious without endlessid (don't crash)

**Comment by zxcvbnma54** [comment]
你好我也有相同問題，貌似是此作者的方法，在MOD介紹就有說道：https://github.com/FalsePattern/EndlessIDs
google translate below：▼
Hello, I also have the same problem. It seems to be the author's method. It is said in the MOD introduction:https://github.com/FalsePattern/EndlessIDs

重點：Mods not listed here may or may not work.
Important: Mods not listed here may or may not work.

For item/block IDs:
A good rule of thumb is that the more invasive a mod is, the higher the chance it's broken without a patch once the IDs exceed 4096 and 32000.

**_For biome IDs:
If a mod adds a custom world generator, it has a high chance of invoking an old vanilla method in the worldgen code.
To avoid world corruption and broken biomes, this method has been replaced with an instant crash that refers the user to this github repo._**
