### ISSUE TITLE
[Compatibility Request]: NomadicTents

### ISSUE THREAD

**Issue by GamebP** [FalsePattern/EndlessIDs#51]
### Other mod's name

NomadicTents[1.7.10]-1.12.1.jar

### Other mod's homepage

https://github.com/skyjay1/Nomadic-Tents

### Other mod's license

GPLv3

### Game log

[2022-10-08-7.log.gz](https://github.com/FalsePattern/EndlessIDs/files/9737857/2022-10-08-7.log.gz)

### Description

Found this error beacuse it dosen't like alot of mods in one big coconut pile. I think..
Im here just trying to make the biggest minecraft modpack.. well im kinda getting there..

Even if you don't make a compatibility with this mod, i'll delete it beacuse it's nothing.

So i tested NomadicTents without the results are it's working without it. But i could be wrong.

**Comment by quentin452** [comment]
nomadic tents its work for me, i think is duplicate issue of
https://github.com/FalsePattern/EndlessIDs/issues/46

**Comment by GamebP** [comment]
> nomadic tents is work for me, i think is duplicate issue of #46 edit : i maked a tent and the game crashed

i don't understand?

**Comment by quentin452** [comment]
I was wrong :D that's why there is an edit

**Comment by GamebP** [comment]
I can't do nothing about it, i haven't used cofh core to tp to it. beacuse i don't know the commands. Eather way.. I don't know the problem or im just blind

**Comment by GamebP** [comment]
> I was wrong :D that's why there is an edit

Aha alright.

**Comment by quentin452** [comment]
it's just that there are several mods in your modpack that are incompatible with endlessids

**Comment by GamebP** [comment]
you mean 350+=> mods?
makes sence but i try to find a way to get arround this.
It wont work beacuse of alot of mods.

**Comment by quentin452** [comment]
?

**Comment by quentin452** [comment]
can you reopen the issue?

**Comment by GamebP** [comment]
> can you reopen the issue? it's not because there are a lot of mods

**what then is the problem?**

**Comment by quentin452** [comment]
various witchery ,nomadic tents are incompatible with endlessids and maybe more in your modpack

**Comment by GamebP** [comment]
I'll remove nomadic tents and wait till its compatable with witchary & the thents. 
I can't remove endless ids mod beacuse almost every mod is using it

**Comment by quentin452** [comment]
ok

**Comment by quentin452** [comment]
I advise you to install cofh core and use this command /cofh tpx (id of dimensionds) to see if other mods are incompatible

**Comment by GamebP** [comment]
cofh core was installed 7days ago by onother mod.

**Comment by quentin452** [comment]
ok

**Comment by GamebP** [comment]
whats your discord?

**Comment by quentin452** [comment]
I'm A Cat[FR]#7202

**Comment by FalsePattern** [comment]
[removed social media information]
