### ISSUE TITLE
[Compatibility Request]: Twilight Forest

### ISSUE THREAD

**Issue by fn2006** [FalsePattern/EndlessIDs#6]
### Other mod's name

Twilight Forest

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest

### Other mod's license

Other open source license (please specify in the description)

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/9073165/fml-client-latest.log)

### Description

The mod's license is LGPLv2.1.
The game crashes when I enter the twilight forest portal, the logs told me to create an issue here.

**Comment by FalsePattern** [comment]
Fixed in 1.4.0 Alpha 9
