### ISSUE TITLE
[Compatibility Request]: LOTR and LOTR Extended support.

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/EndlessIDs#62]
### Other mod's name

Title.

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/the-lord-of-the-rings-mod-legacy and https://www.curseforge.com/minecraft/mc-mods/lotr-extended.

### Other mod's license

 I have no clue what LOTR's license is, and I can't do much about it being closed-source, so yell at the devs. This has been an issue ever since I heard of EIDs.

### Game log

https://pastebin.com/yRbJKcSk

### Description

Title.

**Comment by quentin452** [comment]
for lotr #33

**Comment by MagmaBro123** [comment]
Oh, whoops.

**Comment by FalsePattern** [comment]
Duplicate of #33
