### ISSUE TITLE
[Compatibility Request]: enderlicious

### ISSUE THREAD

**Issue by kotmatross28729** [FalsePattern/EndlessIDs#66]
### Other mod's name

Enderlicious

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/enderlicious

### Other mod's license

All Rights Reserved

### Game log

[latest.log](https://github.com/FalsePattern/EndlessIDs/files/9938501/latest.log)

### Description

if enderlicious and endless ids are installed, then the game crashes when entering end

**Comment by FalsePattern** [comment]
see #48
