### ISSUE TITLE
[Compatibility Request]: Thaumcraft

### ISSUE THREAD

**Issue by SatakeKanrin** [FalsePattern/EndlessIDs#7]
### OS

Windows

### GPU

NVIDIA

### Game log

[latest.log](https://github.com/FalsePattern/EndlessIDs/files/9078257/latest.log)

### Description

The minecraft crashed after entering a newly created world
[crash-2022-07-10_09.52.45-server.txt](https://github.com/FalsePattern/EndlessIDs/files/9078255/crash-2022-07-10_09.52.45-server.txt)
.

**Comment by FalsePattern** [comment]
Fixed in 1.4.0 Alpha 9
