### ISSUE TITLE
[Compatibility Request]: Enderlicious

### ISSUE THREAD

**Issue by Temeraro** [FalsePattern/EndlessIDs#72]
### Other mod's name

Potentials: Thaumcraft, HEE, Village Names, EvilCraft, Highlands, Betweenlands, Erebus, Twilight, Forgotten Nature

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/thaumcraft

### Other mod's license

AGPLv3

### Game log

[crash-2022-12-20_15.25.11-server.txt](https://github.com/FalsePattern/EndlessIDs/files/10266295/crash-2022-12-20_15.25.11-server.txt)

### Description

https://paste.atlauncher.com/view/7c0d92c2-9c45-4443-838d-7adaad6a77b3

**Comment by FalsePattern** [comment]
see #48
