### ISSUE TITLE
[Bug]: Modpack crashing on mod loading screen

### ISSUE THREAD

**Issue by gmnovakrc** [FalsePattern/EndlessIDs#75]
### OS

Windows

### GPU

NVIDIA

### Game log

[latest.log](https://github.com/FalsePattern/EndlessIDs/files/10312395/latest.log)

### Description

Custom modpack, making only for friends. 
Using Technic launcher, launch modpack, gets most of way through "loading/initializing mods, phase 3" then crashes.
Seems to be "Anti ID Conflict" mod according to logs, not sure though.

**Comment by FalsePattern** [comment]
Spaces in mod jar names are not supported. Rename your files and remove the spaces from all of them.

**Comment by gmnovakrc** [comment]
> Spaces in mod jar names are not supported. Rename your files and remove the spaces from all of them.

I thought that the actual mod name was defined in the .jar file itself and that the external name could be changed without effecting the mod?

**Comment by embeddedt** [comment]
Because of how mixins are currently designed in 1.7.10, most patch mods locate their targets based on the name of the JAR file, not the name of the mod itself.

**Comment by gmnovakrc** [comment]
> Because of how mixins are currently designed in 1.7.10, most patch mods locate their targets based on the name of the JAR file, not the name of the mod itself.

Can I just remove the spaces or should I put them back to original/default name?
