### ISSUE TITLE
[Bug]: release 1.4.0 does not work with gtnhmixins (beta 3 worked)

### ISSUE THREAD

**Issue by kotmatross28729** [FalsePattern/EndlessIDs#77]
### OS

Windows

### GPU

NVIDIA

### Game log

[latest.log](https://github.com/FalsePattern/EndlessIDs/files/10314211/latest.log)

### Description

I still don’t understand why since release 1.4.0 it stopped loading with gtnh mixins and requires exactly gas station 5.0
But 3 beta 1.4.0 ran fine with gtnh mixins and there was no such dependency on gas station, I don't think it's a problem with the mixins version, because I can also write the 0.8.5 mixins version in the 3 beta and it will still run

**Comment by FalsePattern** [comment]
I don't support gtnhmixins. If you want to use my mod in gtnh, you're free to fork it and fix it yourself.
