### ISSUE TITLE
[Bug]: Some mixin issue

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/EndlessIDs#9]
### OS

Windows

### GPU

AMD

### Game log

[latest.log](https://github.com/FalsePattern/EndlessIDs/files/9080661/latest.log)
https://pastebin.com/tWcmVAjq

### Description

Title.

**Comment by FalsePattern** [comment]
it seems like the prelease i shared in the other issue is broken for some reason. this issue will probably be fixed in alpha 10, which will be build using the clean github runner

**Comment by MagmaBro123** [comment]
Ah, mk

**Comment by FalsePattern** [comment]
Fixed in 1.4 Alpha 10
