### ISSUE TITLE
Update Notifier is very far behind.

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/EndlessIDs#96]
### OS

Windows

### GPU

AMD

### Game log

N/A.

### Description

Title.

![2023-03-03_19 44 37](https://user-images.githubusercontent.com/51277766/222871908-208e473f-7930-489d-ba28-6c0bd8925ed6.png)

**Comment by FalsePattern** [comment]
Alpha releases are not tracked by the updater system, because they're highly experimental and unstable. You can turn off the update checker in the fplib config.

**Comment by MagmaBro123** [comment]
Ah, sorry. Didn't know.
